<?php

namespace xepan\commerce;

class Model_Quotation extends \xepan\hr\Model_Document{
	public $status = ['Draft','Submitted','Approved','Redesign','Rejected','Converted'];
	public $actions = [
					'Draft'=>['view','edit','delete','submit','manage_attachments'],
					'Submitted'=>['view','edit','delete','redesign','reject','approve'],
					'Approved'=>['view','edit','delete','redesign','reject','send'],
					'Redesign'=>['view','edit','delete','submit','reject'],
					'Rejected'=>['view','edit','delete'],
					'Converted'=>['view','edit','delete','send']
					];

	function init(){
		parent::init();

		$quotation_j = $this->join('quotation.document_id'); 

		$quotation_j->hasOne('xepan\base\Contact','contact_id');
		$quotation_j->hasOne('xepan\commerce\TNC','tnc_id');
		$quotation_j->hasMany('xepan\commerce\QuotationItem','quotation_id');

		// $quotation_j->hasOne('xepan\commerce\Currency','currency_id');
		$quotation_j->addField('qt_no')->hint('For Autogenerated, Leave Empty');


		$quotation_j->addField('narration')->type('text');
		$this->addExpression('gross_amount')->set($this->refSQL('xepan\commerce\QuotationItem')->sum('amount'));
		$quotation_j->addField('discount_amount');
		$quotation_j->addField('total_amount')->type('money');
		$quotation_j->addField('tax')->type('money');
		$quotation_j->addField('net_amount')->type('money')->mandatory(true);


		$this->addCondition('type','Quotation');

	}

		function submit(){
		$this['status']='Draft';
		$this->saveAndUnload();
	}

		function reject(){
			$this['status']='Submitted';
			$this->saveAndUnload();
	}

	
}
